### PR TITLE
Loosen Dependency Requirements for Python Compatibility by Dropping Mordred

### LINKED ISSUE #240: ```pip install aimsim``` not working on MacOSX
Trace attached
[aimsim_macosx_installation_trace.txt](https://github.com/VlachosGroup/AIMSim/files/10582154/aimsim_macosx_installation_trace.txt)

System details:
Model Name:	MacBook Pro
Model Identifier: MacBookPro17,1
Chip: Apple M1
Total Number of Cores:	8 (4 performance and 4 efficiency)
Memory:	8 GB
System Firmware Version: 7429.81.3
OS Loader Version: 7429.81.3

### PR DESCRIPTION
**Pull request by JacksonBurns**
Attempting to resolve #240 by allowing wider range of numpy versions since the latest builds have better support.

### CODE REVIEW

**Comment by JacksonBurns** [comment]
Related, #219 attempted to do this but we dropped it because it caused backwards compatibility issues with Python. Will attempt to resolve here.

**Comment by JacksonBurns** [comment]
`mordred` [requires an older version of networkx](https://github.com/mordred-descriptor/mordred/blob/c9de906f0d7829a9abe80658b19f4f9f9aef6648/setup.py#L7) to function properly with Python 3.9.

**Comment by JacksonBurns** [comment]
The fixed version of `networkx` is incompatible with moving the version of numpy up -- there is a [PR open to fix this](https://github.com/mordred-descriptor/mordred/pull/90) on the repo but it's stale. Looks like `mordred` has basically been abandoned at this point.

I think that, in order to support future Python versions as well as M1 Macs, we would need to remove `mordred` from the default install. We can make it an optional install, i.e. `pip install aimsim[mordred]` but clarify that such an install is only supported on Python 3.8
The option that I would prefer would be to fork `mordred`, fix the dependency issue, and then include the source code in `AIMSim` with the [appropriate attribution](https://opensource.stackexchange.com/a/7595).
Option 3 is, of course, to just drop `mordred` altogether.
Thoughts @himaghna ?

**Comment by himaghna** [comment]
> The fixed version of `networkx` is incompatible with moving the version of numpy up -- there is a [PR open to fix this](https://github.com/mordred-descriptor/mordred/pull/90) on the repo but it's stale. Looks like `mordred` has basically been abandoned at this point.
> 
> I think that, in order to support future Python versions as well as M1 Macs, we would need to remove `mordred` from the default install. We can make it an optional install, i.e. `pip install aimsim[mordred]` but clarify that such an install is only supported on Python 3.8 The option that I would prefer would be to fork `mordred`, fix the dependency issue, and then include the source code in `AIMSim` with the [appropriate attribution](https://opensource.stackexchange.com/a/7595). Option 3 is, of course, to just drop `mordred` altogether. Thoughts @himaghna ?

I think for the short term we might include modred as an optional install with tags (such as -md or some such). Long term I agree moving it into our base code makes the most sense.

**Comment by himaghna** [comment]
Tests failing

**Comment by JacksonBurns** [comment]
@JacksonBurns this should be accompanied by a beta release, likely `2.0.0b0` so that other changes can continue to be made.

**Comment by JacksonBurns** [comment]
Also see #247 when reevaluating Python minor version compatibility and dependency version requirements.

**Pull request merged**
